import type { NextPage } from 'next';
import { useTheme } from 'next-themes';
import Head from 'next/head';
import React from 'react';
import Hero from '../components/hero';
import Shoutouts from '../components/shoutouts';
import Techniques from '../components/techniques';

const Home: NextPage = () => {
  const { theme, setTheme } = useTheme();
  const [mounted, setMounted] = React.useState<boolean>(false);

  React.useEffect(() => {
    setMounted(true);
  }, [setMounted]);

  if (!mounted) {
    return null;
  }

  return (
    <div className=''>
      <Head>
        <title>Design Agency</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <Hero />
        <Techniques />
        <Shoutouts />
        <div className='mt-20'>
          The current theme is: {theme}
          <button
            onClick={() =>
              theme === 'light' ? setTheme('dark') : setTheme('light')
            }
          >
            Toggle theme
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
